ansible_user: ansibletestuser
ansible_port: 5986
ansible_connection: winrm
ansible_password: p@$$w0rd12
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: certificate
ansible_winrm_scheme: https
ansible_winrm_cert_key_pem: /home/Michael/cert_key.pem
ansible_winrm_cert_pem: /home/Michael/cert.pem

