---
- name: Windows Password Rotation and upload to KeyVault
  hosts: windows
  vars_files:
    - /home/Michael/ansible/host_vars/windowshostvars/windowshost_vars.yml


  vars:
    Windows_User: Michael
    New_Password: "{{ lookup('password', '/tmp/password chars=ascii_letters,digits,punctuation length=14') }}"

  tasks:
    - name: Change password
      win_user:
        name: "{{ Windows_User }}"
        state: present
        password: "{{ New_Password | password_hash('sha512') }}"
    - name: Set up a shared variable to run between plays
      set_fact:
        shared_password_variable: "{{New_Password}}"
        shared_username_variable: "{{Windows_User}}"

- hosts: windows
  connection: local


  tasks:


  - name: Push changed password into KeyVault
    azure_rm_keyvaultsecret:

      # Change secret_name to how you wish the secret to be stored inside the vault ie AnsibleControlNodes-
      secret_name: "{{'BackendDatabases-' + shared_username_variable }}"
      secret_value: "{{ shared_password_variable }}"
      keyvault_uri: https://kv-test3.vault.azure.net/

  - name: Remove Temp File
    ansible.builtin.file:
      path: /tmp/password
      state: absent

