---
- name: Linux Password Rotation and upload to KeyVault
  hosts: linux
  vars_files:
    - /home/Michael/AnsibleProd/host_vars/linuxhostvars/linuxhost_vars.yml

  become: true
  vars:
    linux_user: Michael
    new_password: "{{ lookup('password', '/tmp/password chars=ascii_letters,digits,punctuation length=14') }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Change password
      ansible.builtin.user:
        name: "{{ linux_user }}"
        state: present
        password: "{{ new_password | password_hash('sha512') }}"
    - name: Set up a shared variable to run between plays
      set_fact:
        shared_password_variable: "{{new_password}}"
        shared_username_variable: "{{linux_user}}"

- hosts: linux
  connection: local


  tasks:


  - name: Push changed password into KeyVault
    azure_rm_keyvaultsecret:

      # Change secret_name to how you wish the secret to be stored inside the vault ie AnsibleControlNodes-Michael
      secret_name: "{{'AnsibleControlNodes-' + shared_username_variable }}"
      secret_value: "{{ shared_password_variable }}"
      keyvault_uri: https://kv-test3.vault.azure.net/

  - name: Remove Temp File
    ansible.builtin.file:
      path: /tmp/password
      state: absent

